### ISSUE TITLE
grpc modules has problem 

### ISSUE THREAD

**Issue by minixxie** [alexanderGugel/ied#151]
* **Version**: ied version 2.0.5
* **Platform**: Darwin easyvan 14.5.0 Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64
* **Subsystem**: grpc npm module

ied is blazingly fast! but it has problems on installing grpc module. What I guess is grpc actually requires compilation of C code, I could not see any steps doing the compilation. npm install does have such step. Not sure if my guess is right, may need your comments. Here is the output after I installed grpc modules:

```
simon.tse@easyvan:~/git/public/research-ied$ node index.js 
WARNING: No configurations found in configuration directory:/Users/simon.tse/git/public/research-ied/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/simon.tse/git/public/research-ied/node_modules/734e3c4ad1b6df208f2d0647c1f6402fb141f9dd/package/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/simon.tse/git/public/research-ied/node_modules/734e3c4ad1b6df208f2d0647c1f6402fb141f9dd/package/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

```

**Comment by mgcrea** [comment]
Have you tried `ied install -b` to actually build modules?
