### ISSUE TITLE
Can not install node-sass

### ISSUE THREAD

**Issue by zjiekai** [alexanderGugel/ied#153]
* **Version**: 2.1.0
* **Platform**: Ubuntu 16.04 LTS \n \l 64-bit
* **Subsystem**: 

```
$ ied init
$ ied --registry=http://registry.npm.taobao.org install --save-dev node-sass
$ node_modules/.bin/node-sass -h
fs.js:856
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/home/zjk/transwarp/misc/haha/node_modules/.cas/ec0f89ae6625e1d990dc7ff713b275ea15dfee05/package/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.getInstalledBinaries (/home/zjk/transwarp/misc/haha/node_modules/.cas/ec0f89ae6625e1d990dc7ff713b275ea15dfee05/package/lib/extensions.js:119:13)
    at foundBinariesList (/home/zjk/transwarp/misc/haha/node_modules/.cas/ec0f89ae6625e1d990dc7ff713b275ea15dfee05/package/lib/errors.js:20:15)
    at foundBinaries (/home/zjk/transwarp/misc/haha/node_modules/.cas/ec0f89ae6625e1d990dc7ff713b275ea15dfee05/package/lib/errors.js:15:5)
    at Object.module.exports.missingBinary 
```(/home/zjk/transwarp/misc/haha/node_modules/.cas/ec0f89ae6625e1d990dc7ff713b275ea15dfee05/package/lib/errors.js:45:5)
    at Object.<anonymous> (/home/zjk/transwarp/misc/haha/node_modules/.cas/ec0f89ae6625e1d990dc7ff713b275ea15dfee05/package/lib/index.js:15:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by mgcrea** [comment]
`node-sass` requires building:

try `ied --registry=http://registry.npm.taobao.org install --save-dev node-sass -b`.
