### ISSUE TITLE
scoped modules with specific versions fail to install

### ISSUE THREAD

**Issue by scottbessler** [alexanderGugel/ied#166]
* **Version**: 2.3.2
* **Platform**: Darwin 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin

ied fails when installing specific versions of scoped modules, likely due to https://github.com/npm/npm/issues/9164
which is an open issue of the npm registry api https://github.com/npm/public-api/issues/11

```bash
➜ ied i @types/mocha@2.2.29

/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/rxjs/Observer.js:5
    error: function (err) { throw err; },
                            ^
AssertionError: error status code https://registry.npmjs.org/@types%2Fmocha/2.2.29: undefined
    at checkStatus (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/lib/registry.js:97:20)
    at SafeSubscriber._next (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/lib/registry.js:134:12)
    at SafeSubscriber.__tryOrSetError (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/rxjs/Subscriber.js:232:16)
    at SafeSubscriber.next (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/rxjs/Subscriber.js:174:27)
    at Subscriber._next (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/rxjs/Subscriber.js:89:18)
    at DoSubscriber._next (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/rxjs/operator/do.js:82:24)
    at DoSubscriber.Subscriber.next (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/rxjs/Subscriber.js:89:18)
    at /Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/lib/util.js:91:14
    at done (/Users/scott/.nvm/versions/node/v6.2.2/lib/node_modules/ied/node_modules/needle/lib/needle.js:377:14)

Scoped modules without versions work fine:
```bash
➜ ied i @types/mocha
```

**Comment by aecz** [comment]
Also i cannot find a workaround when a `dist-tag` is used.
For example, in package,json if we have `"@ngtools/webpack" : "latest"`, then running `ied i @ngtools/webpack` does not help. `ied i` still fails with this error:
```
C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Observer.js:5
    error: function (err) { throw err; },
                            ^
AssertionError: error status code https://registry.npmjs.org/@ngtools%2Fwebpack/latest: undefined
    at checkStatus (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\lib\registry.js:97:20)
    at SafeSubscriber._next (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\lib\registry.js:134:12)
    at SafeSubscriber.__tryOrSetError (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:232:16)
    at SafeSubscriber.next (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:174:27)
    at Subscriber._next (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:89:18)
    at DoSubscriber._next (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\operator\do.js:82:24)
    at DoSubscriber.Subscriber.next (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:89:18)
    at C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\lib\util.js:91:14
    at done (C:\Users\aecz\AppData\Roaming\npm\node_modules\ied\node_modules\needle\lib\needle.js:377:14)
```
