### ISSUE TITLE
rxjs\Observer error

### ISSUE THREAD

**Issue by Pszek** [alexanderGugel/ied#172]
I really like your extension. It saved me from getting furious during Windows installs. But now in my project I cannot run ied successfully.
Ordinary 'ied install' doesn't give any error (but is extremely short comparing to npm - 20 times), but gulp process results in failure. 

Following someone's suggestion I tried to do 'ied install -b', which gives me this:

```
'"node-pre-gyp install --fallback-to-build' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Observer.js:5
    error: function (err) { throw err; },
                            ^

function FailedBuildError() {
                _classCallCheck(this, FailedBuildError);

                var _this = _possibleConstructorReturn(this, Object.getPrototypeOf(FailedBuildError).call(this, 'failed to build one or more dependencies that exited with != 0'));

                _this.name = FailedBuildError;
                return _this;
        }: failed to build one or more dependencies that exited with != 0
    at FailedBuildError.Error (native)
    at new FailedBuildError (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\lib\build.js:79:88)
    at SafeSubscriber._next (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\lib\build.js:166:9)
    at SafeSubscriber.__tryOrSetError (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:232:16)
    at SafeSubscriber.next (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:174:27)
    at Subscriber._next (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:89:18)
    at DoSubscriber._next (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\operator\do.js:82:24)
    at DoSubscriber.Subscriber.next (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Subscriber.js:89:18)
    at FilterSubscriber._next (C:\Users\maciejciniewski\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\operator\filter.js:88:30)
```

My version of ied: 2.3.2, platform: Windows 64-bit.
Please show me the ways I can get more info to know the source of the problem or solution to that.

**Comment by mhussain001** [comment]
I am also facing same issue
Here is log
$ ied install
*******\AppData\Roaming\npm\node_modules\ied\node_modules\rxjs\Observer.js:5
    error: function (err) { throw err; },
                                  ^
Error: EPERM, symlink '******\node_modules\bower'
    at Error (native)

**Comment by maroy1986** [comment]
Same issue here. Running as administrator on both Windows and Linux result in the same result described by others above...

**Comment by redaxmedia** [comment]
Same issue here!
