### ISSUE TITLE
ied error during runtime, executed without params, environment is windows 7 pro.

### ISSUE THREAD

**Issue by rcdosado** [alexanderGugel/ied#19]
var debug = util.debuglog('expose')
                 ^
TypeError: Object #<Object> has no method 'debuglog'
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\ied\lib\expose.
js:7:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\ied\lib\install
_cmd.js:7:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by alexanderGugel** [comment]
You're probably using an outdated version of node.
Can you check via `node --version`?

**Comment by rcdosado** [comment]
youre correct, now its running fine on my system, thanks!
