### ISSUE TITLE
No satisfying target found for jsbn

### ISSUE THREAD

**Issue by jvdanilo** [alexanderGugel/ied#30]
I try to install *laravel-elixir* and get:

```
$ ied install laravel-elixir
[======                        ] 19.26%/usr/local/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                 ^

Error: No satisfying target found for jsbn@git+https://github.com/rynomad/jsbn.git
    at /usr/local/lib/node_modules/ied/lib/resolve.js:88:17
    at fetch (/usr/local/lib/node_modules/ied/lib/resolve.js:21:5)
    at resolve (/usr/local/lib/node_modules/ied/lib/resolve.js:80:3)
    at fn (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:741:34)
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:1208:16
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:701:43
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:705:44)
    at install (/usr/local/lib/node_modules/ied/lib/install.js:114:9)
    at /usr/local/lib/node_modules/ied/lib/install.js:38:5
```

**Comment by dylang** [comment]
I got this as well for the same package, then I ran it again and it seemed to finish without an error but there were a lot of missing dependencies.

```
❯ ied i co-request
/private/var/folders/hl/c611mdq92fd6q6_rf_mj33cr0000gp/T ❯ npm ls
/private/var/folders/hl/c611mdq92fd6q6_rf_mj33cr0000gp/T
├──
├─┬ api-bill-forecast-pge@4.0.6
│ ├── function-bind@0.1.0
│ ├── jsonschema@0.4.0
│ ├── lodash@3.10.1
│ ├─┬ lodash.sum@3.6.2
│ │ ├─┬ lodash._basecallback@3.3.1
│ │ │ ├─┬ lodash._baseisequal@3.0.7
│ │ │ │ └── lodash.istypedarray@3.0.2
│ │ │ ├── lodash._bindcallback@3.0.1
│ │ │ └── lodash.pairs@3.0.1
│ │ ├── lodash._baseeach@3.0.4
│ │ ├── lodash._isiterateecall@3.0.9
│ │ ├─┬ lodash._toiterable@3.0.4
│ │ │ └── lodash._basevalues@3.0.0
│ │ ├── lodash.isarray@3.0.4
│ │ └─┬ lodash.keys@3.1.2
│ │   ├── lodash._getnative@3.9.1
│ │   └── lodash.isarguments@3.0.4
│ ├─┬ snuffles@5.9.3
│ │ ├── colors@0.6.2
│ │ ├── lodash@2.4.2
│ │ ├── q@1.4.1
│ │ ├─┬ q-io@1.13.1
│ │ │ ├─┬ collections@0.2.2
│ │ │ │ └── weak-map@1.0.0
│ │ │ ├── mime@1.3.4
│ │ │ ├── mimeparse@0.1.4
│ │ │ ├── qs@1.2.2
│ │ │ └── url2@0.0.0
│ │ ├── tmp@0.0.24
│ │ └── traverse@0.6.6
│ ├── underscore.string@2.4.0
│ └── x-web-angular-resource@1.2.12
├─┬ co-request@1.0.0 -> /private/var/folders/hl/c611mdq92fd6q6_rf_mj33cr0000gp/T/node_modules/8eb5fb656c2ee1e82e36c4ccfe9376846406b260/package
│ └── UNMET DEPENDENCY request@*
├─┬ ecc-jsbn@0.0.1 -> /private/var/folders/hl/c611mdq92fd6q6_rf_mj33cr0000gp/T/node_modules/970577ba31b4976fb1889a298cb7451d896c466d/package
│ └── UNMET DEPENDENCY jsbn@git+https://github.com/rynomad/jsbn.git
└─┬ sshpk@1.7.0 -> /private/var/folders/hl/c611mdq92fd6q6_rf_mj33cr0000gp/T/node_modules/c64ac26de1bdd19cc9ccbe78ba747292c6c70a7c/package
  ├── UNMET DEPENDENCY asn1@>=0.2.3 <0.3.0
  ├── UNMET DEPENDENCY assert-plus@>=0.2.0 <0.3.0
  └── UNMET DEPENDENCY dashdash@>=1.10.1 <2.0.0

npm ERR! missing: request@*, required by co-request@1.0.0
npm ERR! missing: jsbn@git+https://github.com/rynomad/jsbn.git, required by ecc-jsbn@0.0.1
npm ERR! missing: asn1@>=0.2.3 <0.3.0, required by sshpk@1.7.0
npm ERR! missing: assert-plus@>=0.2.0 <0.3.0, required by sshpk@1.7.0
npm ERR! missing: dashdash@>=1.10.1 <2.0.0, required by sshpk@1.7.0
```

**Comment by alexanderGugel** [comment]
GIT dependencies are currently not supported. Please see #7 .
