### ISSUE TITLE
Known issue with eslint

### ISSUE THREAD

**Issue by alexanderGugel** [alexanderGugel/ied#32]
Currently [standard](https://www.npmjs.com/package/standard) is not supported.

This is due to a reported bug in eslint: eslint/eslint#4263

The error will be along the lines of:

```
 % ./node_modules/.bin/standard                                                                                                          ied/example (master) Alexanders-MacBook-Pro
/Users/alex/repos/ied/example/node_modules/2f013912b2794ddb30bbaa89dc13fb3a990cc72b/package/rc/.eslintrc
standard-react
standard: Unexpected linter output:

Error: Cannot find module 'eslint-config-standard-react'
Referenced from: /Users/alex/repos/ied/example/node_modules/2f013912b2794ddb30bbaa89dc13fb3a990cc72b/package/rc/.eslintrc
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at readConfigFromFile (/Users/alex/repos/ied/example/node_modules/a75aaf07e28650772ed0e70daa2ce083079b6514/package/lib/config.js:158:44)
    at loadConfig (/Users/alex/repos/ied/example/node_modules/a75aaf07e28650772ed0e70daa2ce083079b6514/package/lib/config.js:179:22)
    at /Users/alex/repos/ied/example/node_modules/a75aaf07e28650772ed0e70daa2ce083079b6514/package/lib/config.js:210:46
    at Array.reduceRight (native)
    at loadConfig (/Users/alex/repos/ied/example/node_modules/a75aaf07e28650772ed0e70daa2ce083079b6514/package/lib/config.js:194:36)
    at new Config (/Users/alex/repos/ied/example/node_modules/a75aaf07e28650772ed0e70daa2ce083079b6514/package/lib/config.js:388:38)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues
```

**Comment by alexanderGugel** [comment]
Nothing we can do about that.

**Comment by sterpe** [comment]
This is not a bug in standard it's due to the issues surrounding symlinking and the expectation that symlinks aren't resolved when in fact require does resolve them.

**Comment by alexanderGugel** [comment]
No, this is due to the fact that eslint implicitly relies on npm's nested (even after v3) dependency graph to load shared configuration files.
