### ISSUE TITLE
TypeError: Object #<Object> has no method 'debuglog'

### ISSUE THREAD

**Issue by goliatone** [alexanderGugel/ied#37]
The module maybe should check the node version and inform the user the current version is not supported?

```
node --version // v0.10.26
```

```
ied install commander
```

```
/usr/local/lib/node_modules/ied/lib/expose.js:8
var debug = util.debuglog('expose')
                 ^
TypeError: Object #<Object> has no method 'debuglog'
    at Object.<anonymous> (/usr/local/lib/node_modules/ied/lib/expose.js:8:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ied/lib/install_cmd.js:7:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

mac os x 10.10.5

**Comment by alexanderGugel** [comment]
It probably should.
