### ISSUE TITLE
IED behind proxy part 2

### ISSUE THREAD

**Issue by wdjunaidi** [alexanderGugel/ied#40]
A few issues that I found testing `ied` behind proxy:

1. It expects `HTTP_PROXY` environment variable in all caps; most unix/linux/mac command line tools work with lower case `http_proxy`, these includes `npm` and `git`.

2. Initial run of `ied install` against a react-webpack tutorial project produced this error messages:

```
/xxx/v5.1.0/lib/node_modules/ied/lib/expose.js:47
    debug('expose %s in %s', pkg.dist.shasum, dir)

TypeError: Cannot read property 'dist' of undefined
    at expose (/xxx/node/v5.1.0/lib/node_modules/ied/lib/expose.js:47:31)
    at /xxx/node/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:356:13)
    at async.forEachOf.async.eachOf (/xxx/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:233:31)
    at _asyncMap (/xxx/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:359:9)
    at Object.map (/xxx/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:359:9)
    at expose (/xxx/node/v5.1.0/lib/node_modules/ied/lib/expose.js:42:11)
    at fn (/xxx/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:741:34)
    at /xxx/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:1208:16
    at /xxx/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
    at /xxx/v5.1.0/lib/node_modules/ied/node_modules/async/lib/async.js:701:43
```

3. I thought I gave it another run, so I re-run `ied install` and got the following message:

```
/xxx/v5.1.0/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                 ^

Error: No satisfying target found for jsbn@git+https://github.com/rynomad/jsbn.git
    at /xxx/v5.1.0/lib/node_modules/ied/lib/resolve.js:83:17
    at resolvePending (/xxx/v5.1.0/lib/node_modules/ied/lib/resolve.js:15:25)
    at IncomingMessage.<anonymous> (/xxx/v5.1.0/lib/node_modules/ied/lib/resolve.js:57:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

**Comment by faceleg** [comment]
Hi @wdjunaidi! Thanks for picking up the baton, I didn't get a chance to test #33 behind my proxy yet.

**Comment by alexanderGugel** [comment]
Huhuhu perfect! Thanks for testing this!

This is definitely of high priority, so I'm gonna work on this tomorrow night or so. If anyone wants to give it a try, please do!

**Comment by alexanderGugel** [comment]
I'm assuming it works. We're now using `needle`'s proxy option, so this should be fairly reliable.
