### ISSUE TITLE
getaddrinfo ENOTFOUND vs https registry

### ISSUE THREAD

**Issue by timoxley** [alexanderGugel/ied#43]
When trying to install this particular package `ied` does a bit of work, then fails with a weird `getaddrinfo ENOTFOUND` error:

```
> ied install css-loader
[==============================] 100.00%/usr/local/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                 ^

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
>
```

Switching to the https registry does work though:

```
> ied install --registry=https://registry.npmjs.org/ css-loader
> 
```

**edit:** not sure switching the `--registry` actually fixed anything, seems intermittent.

Regardless of this bug, perhaps should default to the https endpoint.

```
> ied --version
ied version 0.3.4
> node --version
v4.2.2
```

**Comment by alexanderGugel** [comment]
Uhh that is strange. I can't really explain it, but yes, we should use of course use HTTPS.

This might have also produced an inconsistent `node_modules` directory (problem with way we currently prevent deadlocks), therefore you might have to blow away `node_modules` after `ied` failed. This sucks and will be resolved.

**Comment by timoxley** [comment]
Not sure this was actually resolved… the `ENOTFOUND` persists regardless of the `https` or not… but the error doesn't make sense to me so I looked elsewhere for possible workarounds…

So I found a weird way to get it to work though, by setting the http/https agent to keepAlive connections for 5s in  `[lib/protocol_to_agent.js](https://github.com/alexanderGugel/ied/blob/master/lib/protocol_to_agent.js#L16-L20)`:

```js
var agentConfig = {
  keepAlive: true,
  keepAliveMsecs: 5000
}

var protocolToAgent = {
  'http:': httpProxy || new http.Agent(agentConfig),
  'https:': httpsProxy || new https.Agent(agentConfig)
}
```

I have seen the `ENOTFOUND` once since setting this, so apparently it doesn't cure it entirely, but after multiple clean installs I have only seen the issue return once.

----

Would be interested to see if this has any negative or positive performance impact, because this was blocking me from installing anything, I have no baseline to compare against, other than npm itself.

Compare ied and npm installing the same package.json:

#### ied
```
> rm -Rf ./node_modules && rm -Rf ~/.ied_cache
> time ied install
ied install  8.33s user 3.32s system 95% cpu 12.204 total
```
#### npm 2.14.7
```
> rm -rf ./node_modules # not cleaning npm cache because slow enough as-is.
> time npm install
npm install --silent  51.60s user 20.30s system 114% cpu 1:02.74 total
```

**Comment by alexanderGugel** [comment]
Uhh that is weird. Yeah, maybe we just need to use `keepAlive`.

**Comment by srgpqt** [comment]
I'm also experiencing this issue sporadically with ied version 0.3.6

**Comment by timoxley** [comment]
@alexanderGugel please reopen, this was accidentally re-closed in a rebase I think.

**Comment by zeke** [comment]
I'm having this issue with 0.3.6 too:

```
❯ time ied install jus
[==============================] 99.93%/usr/local/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                 ^

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
ied install jus  2.73s user 0.70s system 79% cpu 4.340 total

❯ ied -v
ied version 0.3.6
```

**Comment by just-boris** [comment]
I guess that add retry request can help here.

**Comment by Qix-** [comment]
Still getting this intermittently. It was on the first install using IED, but was on a random module after a bunch of others succeeded. A retry would be great.

**Comment by just-boris** [comment]
Since `0.4.0` we are using [`got`](https://github.com/sindresorhus/got) for request. It makes up to 5 retries on errors.

@Qix- you can help if you run `ied install` with `NODE_DEBUG=fetch` environment property set and send console output here. Maybe we can figure out something.

**Comment by Qix-** [comment]
Unfortunately I ran into other issues with ied, namely when trying to use `electron-prebuilt`. Had to switch back to npm.

**Comment by just-boris** [comment]
I guess it was because postinstall scripts do not work here now. Sorry.

@alexanderGugel do we have an issue about npm lifecycle scripts? It helps guys to keep tracking it.

**Comment by zeke** [comment]
```
❯ ied -v
ied version 0.4.3

❯ node -v
v5.3.0

❯ ied install jus
[==============================] 100.00%
/usr/local/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                 ^
RequestError: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/ied/node_modules/got/index.js:68:21)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:998:8)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```

**Comment by schickling** [comment]
Hitting the same problem

**Comment by timoxley** [comment]
@alexanderGugel @zeke I wonder if it's possible that the sheer number of requests is overloading the local network hardware?

**Comment by timoxley** [comment]
Though… npm somehow gets around this.

**Comment by Qix-** [comment]
If it was overloading the local hardware it shouldn't be getting DNS misses, it'd be either a refusal or a timeout I would imagine.

**Comment by timoxley** [comment]
@Qix- yeah you're probably right, the dns entries should be in the local cache anyway. Perhaps it's an issue with OS X's dns handling? @Qix- Any other ideas what could cause this?

**Comment by Qix-** [comment]
Not a clue. Seems random at best and non-reproducible at worst. :/ My _favorite_ kind of bug. /s

**Comment by alexanderGugel** [comment]
@Qix- Yes, we're using [got](https://www.npmjs.org/package/got), but will be moving away from it in the RxJS rewrite. Looked through their source, but shouldn't affect timeout.

**Comment by jippi** [comment]
I'm getting hit by the same bug - though I think its a kernel issue.. 

If i run a `ping` command at the same time, i get the following error(s) at the same time `ied`  fails to download

```
64 bytes from 8.8.8.8: icmp_req=332 ttl=63 time=27525 ms
64 bytes from 8.8.8.8: icmp_req=333 ttl=63 time=26547 ms
64 bytes from 8.8.8.8: icmp_req=334 ttl=63 time=25559 ms
64 bytes from 8.8.8.8: icmp_req=335 ttl=63 time=24574 ms
64 bytes from 8.8.8.8: icmp_req=336 ttl=63 time=23583 ms
WARNING: kernel is not very fresh, upgrade is recommended.
From 10.0.2.15: icmp_seq=345 Destination Host Unreachable
From 10.0.2.15: icmp_seq=346 Destination Host Unreachable
From 10.0.2.15: icmp_seq=347 Destination Host Unreachable
From 10.0.2.15: icmp_seq=348 Destination Host Unreachable
From 10.0.2.15: icmp_seq=349 Destination Host Unreachable
From 10.0.2.15: icmp_seq=350 Destination Host Unreachable
From 10.0.2.15: icmp_seq=351 Destination Host Unreachable
From 10.0.2.15: icmp_seq=352 Destination Host Unreachable
From 10.0.2.15: icmp_seq=353 Destination Host Unreachable
From 10.0.2.15: icmp_seq=354 Destination Host Unreachable
From 10.0.2.15: icmp_seq=355 Destination Host Unreachable
From 10.0.2.15: icmp_seq=356 Destination Host Unreachable
From 10.0.2.15: icmp_seq=357 Destination Host Unreachable
From 10.0.2.15: icmp_seq=358 Destination Host Unreachable
From 10.0.2.15: icmp_seq=359 Destination Host Unreachable
From 10.0.2.15: icmp_seq=360 Destination Host Unreachable
From 10.0.2.15: icmp_seq=361 Destination Host Unreachable
From 10.0.2.15: icmp_seq=362 Destination Host Unreachable
From 10.0.2.15: icmp_seq=363 Destination Host Unreachable
From 10.0.2.15: icmp_seq=364 Destination Host Unreachable
From 10.0.2.15: icmp_seq=365 Destination Host Unreachable
From 10.0.2.15: icmp_seq=366 Destination Host Unreachable
From 10.0.2.15: icmp_seq=367 Destination Host Unreachable
From 10.0.2.15: icmp_seq=368 Destination Host Unreachable
From 10.0.2.15: icmp_seq=369 Destination Host Unreachable
From 10.0.2.15: icmp_seq=370 Destination Host Unreachable
From 10.0.2.15: icmp_seq=371 Destination Host Unreachable
From 10.0.2.15: icmp_seq=372 Destination Host Unreachable
From 10.0.2.15: icmp_seq=373 Destination Host Unreachable
From 10.0.2.15: icmp_seq=374 Destination Host Unreachable
From 10.0.2.15: icmp_seq=375 Destination Host Unreachable
From 10.0.2.15: icmp_seq=376 Destination Host Unreachable
64 bytes from 8.8.8.8: icmp_req=377 ttl=63 time=2164 ms
``
