### ISSUE TITLE
Initialize a new package does not work on Windows

### ISSUE THREAD

**Issue by mrmlnc** [alexanderGugel/ied#54]
#### Description
As i understand from the documentation, command `ied init` is an alternative to `npm init`. I write in the console `ied init` and get error.

#### Versions: 
**OS**: Windows 10 x64 (10.0.10586)
**nvm**: v1.1.0 ([nvm-windows](https://github.com/coreybutler/nvm-windows))
**Node.js**: v4.2.4 (x64)
**npm**: v2.14.12
**ied**: v0.3.6

#### Console input
```shell
$ ied init
```

#### Console output
```js
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at initCmd (C:\Users\jacke\AppData\Roaming\nvm\v4.2.4\node_modules\ied\lib\init_cmd.js:7:23)
    at C:\Users\jacke\AppData\Roaming\nvm\v4.2.4\node_modules\ied\bin\cmd.js:89:7
    at Object.<anonymous> (C:\Users\jacke\AppData\Roaming\nvm\v4.2.4\node_modules\ied\bin\cmd.js:100:2)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by alexanderGugel** [comment]
This seems to be due to the fact that the HOME env var doesn't exist under Windows (I assume).

This is implemented here: https://github.com/alexanderGugel/ied/blob/master/lib/init_cmd.js#L7
We could use [`os-homedir`](https://www.npmjs.com/package/os-homedir) to solve this issue. PR welcome.

Should be easy to fix. Want to give it a shot?
