### ISSUE TITLE
Problems combined with deployment tools such as Laravel Forge or executing using node child_process

### ISSUE THREAD

**Issue by cyberkiko** [alexanderGugel/ied#85]
This is the error: 

/usr/lib/node_modules/ied/lib/progress.js:30
    process.stderr.cursorTo(0)
                   ^
TypeError: Object #<SyncWriteStream> has no method 'cursorTo'
    at Object.progress.draw (/usr/lib/node_modules/ied/lib/progress.js:30:20)
    at Object.progress.start (/usr/lib/node_modules/ied/lib/progress.js:23:10)
    at fetchFromRegistry (/usr/lib/node_modules/ied/lib/fetch.js:16:12)
    at ReadStream.<anonymous> (/usr/lib/node_modules/ied/lib/fetch.js:70:5)
    at ReadStream.emit (events.js:95:17)
    at fs.js:1513:12
    at Object.oncomplete (fs.js:107:15)

**Comment by alexanderGugel** [comment]
What Node version are you on?

**Comment by cyberkiko** [comment]
I'm using node 5.6.0, npm 3.6.0

**Comment by parshap** [comment]
`process.stdout.cursorTo` only exists when stdout is a tty:

```
$ node --version
v4.3.0
$ node -e 'console.error(process.stdout.cursorTo)'
[Function]
$ node -e 'console.error(process.stdout.cursorTo)' > /dev/null
undefined
```

**Comment by alexanderGugel** [comment]
Hmm I guess a simple `process.stderr.isTTY` check should fix it

**Comment by alexanderGugel** [comment]
Should be fixed. Thanks!

**Comment by cyberkiko** [comment]
Now it works, thanks ;)
